// <auto-generated />
using System;
using BankManagement.DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankManagement.DAL.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20230509081044_fixSomeColumns")]
    partial class fixSomeColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankManagement.DAL.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 9, 12, 10, 44, 22, DateTimeKind.Local).AddTicks(8788),
                            Name = "Kapital Bank "
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 9, 12, 10, 44, 22, DateTimeKind.Local).AddTicks(8807),
                            Name = "ABB"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 9, 12, 10, 44, 22, DateTimeKind.Local).AddTicks(8810),
                            Name = "Merkezi Bank"
                        });
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<decimal>("CashBack")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Comission")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpireYear")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxCapacity")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("CardTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankId = 1,
                            CashBack = 0m,
                            Comission = 10m,
                            CreatedAt = new DateTime(2023, 5, 9, 12, 10, 44, 22, DateTimeKind.Local).AddTicks(9224),
                            ExpireYear = 3,
                            MaxCapacity = 10000m,
                            Name = "Bir Kart"
                        },
                        new
                        {
                            Id = 2,
                            BankId = 1,
                            CashBack = 5m,
                            Comission = 0m,
                            CreatedAt = new DateTime(2023, 5, 9, 12, 10, 44, 22, DateTimeKind.Local).AddTicks(9229),
                            ExpireYear = 5,
                            MaxCapacity = 5000m,
                            Name = "Premium Kart"
                        },
                        new
                        {
                            Id = 3,
                            BankId = 2,
                            CashBack = 0m,
                            Comission = 5m,
                            CreatedAt = new DateTime(2023, 5, 9, 12, 10, 44, 22, DateTimeKind.Local).AddTicks(9232),
                            ExpireYear = 3,
                            MaxCapacity = 20000m,
                            Name = "Tam Kart"
                        },
                        new
                        {
                            Id = 4,
                            BankId = 2,
                            CashBack = 10m,
                            Comission = 0m,
                            CreatedAt = new DateTime(2023, 5, 9, 12, 10, 44, 22, DateTimeKind.Local).AddTicks(9235),
                            ExpireYear = 5,
                            MaxCapacity = 10000m,
                            Name = "Gənc Kart"
                        },
                        new
                        {
                            Id = 5,
                            BankId = 3,
                            CashBack = 0m,
                            Comission = 5m,
                            CreatedAt = new DateTime(2023, 5, 9, 12, 10, 44, 22, DateTimeKind.Local).AddTicks(9237),
                            ExpireYear = 3,
                            MaxCapacity = 100000m,
                            Name = "Mərkəz Kart"
                        });
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pincode")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusKey = "Waiting",
                            StatusValue = "Gözləyir"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusKey = "Accepted",
                            StatusValue = "Qəbul edildi"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusKey = "Cancelled",
                            StatusValue = "Ləğv edildi"
                        });
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Pin")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.UserCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CVV")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Pincode")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.HasIndex("Number", "CVV", "Pincode")
                        .IsUnique();

                    b.ToTable("UserCards");
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.CardType", b =>
                {
                    b.HasOne("BankManagement.DAL.Entities.Bank", "Bank")
                        .WithMany("CardType")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.Order", b =>
                {
                    b.HasOne("BankManagement.DAL.Entities.CardType", "CardType")
                        .WithMany()
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankManagement.DAL.Entities.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankManagement.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardType");

                    b.Navigation("OrderStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.UserCard", b =>
                {
                    b.HasOne("BankManagement.DAL.Entities.CardType", "Card")
                        .WithMany("Users")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankManagement.DAL.Entities.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.Bank", b =>
                {
                    b.Navigation("CardType");
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.CardType", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BankManagement.DAL.Entities.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
